name = "maxpain-api"
main = "src/index.ts"
compatibility_date = "2025-06-01"

[[d1_databases]]
binding = "DB"
database_name = "maxpain-db"
database_id = "3efbb89c-d56b-407d-a0d3-bb4245c412b9"

[vars]
API_KEY = "MYW1Ku-gD5C9CZBIUWP753ljADzu3D-4BPnXIMic0Qc"
